### ISSUE TITLE
Default installation means that any included SASS files don't have access to Foundation variables

### ISSUE THREAD

**Issue by omobono** [foundation/foundation-rails#182]

**Comment by jasperdavey** [comment]
+1 having the same issue. When trying to precompile my assets, i'm getting Sass::SyntaxError: Undefined variable: "$primary-color".

**Comment by omarwaleed** [comment]
i use aws elastic beanstalk for deployment. what i did is that i precompiled my assets first and then deployed the app with the precompilation
