### ISSUE TITLE
responsive toggle not working

### ISSUE THREAD

**Issue by panaak** [foundation/foundation-rails#187]
hi,

just tried to install clean rails app with the latest `foundation-rails 6.2.0.1`

found out responsive toggle doesn't quite work.

```
.title-bar{"data-hide-for" => "medium", "data-responsive-toggle" => "example-menu"}
  %button.menu-icon{"data-toggle" => "", :type => "button"}
  .title-bar-title Menu
#example-menu.top-bar
  .top-bar-left
    %ul.dropdown.menu{"data-dropdown-menu" => ""}
      %li.menu-text Site Title
      %li.has-submenu
        %a{:href => "#"} One
        %ul.submenu.menu.vertical{"data-submenu" => ""}
          %li
            %a{:href => "#"} One
          %li
            %a{:href => "#"} Two
          %li
            %a{:href => "#"} Three
      %li
        %a{:href => "#"} Two
      %li
        %a{:href => "#"} Three
  .top-bar-right
    %ul.menu
      %li
        %input{:placeholder => "Search", :type => "search"}/
      %li
        %button.button{:type => "button"} Search
```

this is the example code from [foundation website](http://foundation.zurb.com/sites/docs/responsive-navigation.html)

the motion plugins are imported, the css files are in place. still the menu doesn't toggle and the menu-icon isn't displayed.

dont' know if it is a foundation's or foundation-rails'es problem..

**Comment by decabeza** [comment]
It seems to fails from **6.2.4.0** version.

By the moment you can specifies previous version in your Gemfile:

`gem 'foundation-rails', '6.2.3.0'`

If you use **turbolinks** also check https://github.com/zurb/foundation-rails/issues/201

**Comment by decabeza** [comment]
Hi @panaak,

Try to add  `@include foundation-menu-icon` on `foundation_and_overrides.scss` file.

Works for me! 😉
