### ISSUE TITLE
Doesn't work with Sprockets 4 beta 2

### ISSUE THREAD

**Issue by noelrappin** [foundation/foundation-rails#195]
Not sure whether this is premature, but the sprockets-es6 support in foundation-rails collides with the support in Sprockets 4 beta 2.

```
Gem Load Error is: undefined method `register_engine' for Sprockets:Module
Did you mean?  register_pipeline
Backtrace for gem load error is:
/Users/noel/.rvm/gems/ruby-2.3.1@snow_globe/gems/sprockets-es6-0.9.0/lib/sprockets/es6.rb:90:in `<module:Sprockets>'
/Users/noel/.rvm/gems/ruby-2.3.1@snow_globe/gems/sprockets-es6-0.9.0/lib/sprockets/es6.rb:6:in `<top (required)>'
/Use
```

**Comment by SirBertly** [comment]
Any luck with this problem?

**Comment by gowtham-peel** [comment]
@noelrappin are you able to resolve this issue? I'm also facing the same problem. Appreciate your help

**Comment by shadoath** [comment]
Still nothing?  It would be great to have a way to include gem css and js files.
