### ISSUE TITLE
select "appearance: none" not working - missing classes

### ISSUE THREAD

**Issue by anativ** [foundation/foundation-rails#216]
missing classes for "select"
  -moz-appearance:none;
  -webkit-appearance:none;
  -ms-appearance:none;

**Comment by Deckluhm** [comment]
As explained [here](http://foundation.zurb.com/sites/docs/sass.html#autoprefixer-required), vendor prefixes aren't included in sources.

Use the [`autoprefixer-rails` gem](https://github.com/ai/autoprefixer-rails) if you want automatic prefixes.
