### ISSUE TITLE
Undefined mixin 'foundation-global-styles'.

### ISSUE THREAD

**Issue by AmberWilkie** [foundation/foundation-rails#218]
I'm getting this error directly after the generator runs. None of the mixins are working. I have the `sass-rails` gem included in the `Gemfile` (comes with installation)

My `application.scss` looks like this:
```
 *= require font-awesome
 *= require foundation_and_overrides
 *= require_tree .
 *= require_self
```
Here's the link to the code: https://github.com/AmberWilkie/snack-app/tree/navbar

Thanks so much for any insights!

**Comment by Deckluhm** [comment]
You have CSS versions of Foundation in your `app/assets/stylesheets` directory and I think [this line](https://github.com/AmberWilkie/snack-app/blob/navbar/app/assets/stylesheets/foundation_and_overrides.scss#L4) which is supposed to `@import` the SCSS version of Foundation (contained in the gem) is instead importing this one.

So just remove [`foundation.css`](https://github.com/AmberWilkie/snack-app/blob/navbar/app/assets/stylesheets/foundation.css) and [`foundation.min.css`](https://github.com/AmberWilkie/snack-app/blob/navbar/app/assets/stylesheets/foundation.min.css) from the [`app/assets/stylesheets`](https://github.com/AmberWilkie/snack-app/blob/navbar/app/assets/stylesheets) directory and it should work.

**Comment by interpegasus** [comment]
Removing foundation.css and foundation.min.css solved the issue on my end. Thanks

**Comment by kenan-memis** [comment]
I don't have any foundation css files under my assets, but still I do not have access to sass variables like $white from gem files. I also comment out from foundation_and_overrides.scss file, still not working. I use Rails 5.1.2 and gem version 5.4.5.0
