### ISSUE TITLE
Foundation-6 not reloading CSS

### ISSUE THREAD

**Issue by codemaster730** [foundation/foundation-rails#241]
Hi , after wasting so much time on installing Foundation6 on my rails websites, I found it difficult to make a drop-down menu which is copied from Foundation tutorial. 
I'm looking for a good documentation with proper samples and detailed guideline. 
Thanks !

**Comment by cgibsonmm** [comment]
Same still I have turned away from foundation multiple times now because there is horrible docs on how to get get the js to work.
