### ISSUE TITLE
Globals gets repeated many times

### ISSUE THREAD

**Issue by Mathieu-C** [foundation/foundation-rails#244]
Using foundation-rails on Rails 5.1.3 with sass-rails I get this output in my CSS:

![global_duplicate](https://user-images.githubusercontent.com/9420646/31502099-68c3fcb8-af6c-11e7-9c59-8b10afaa3c4f.png)

It seems to be quite [an old issue that was apparently solved](https://foundation.zurb.com/forum/posts/19189-globals-are-repeated-multiple-times) but it doesn't seems to be the case for me.

**Comment by rubenavilah** [comment]
The same here 👎  Anyone has the same Issue?
