### ISSUE TITLE
Ruby Sass ("sass" gem) will be end-of-life March 26th 2019 - Consider switching to "sassc-rails" or "sassc"

### ISSUE THREAD

**Issue by jkimmeyer** [foundation/foundation-rails#278]
Out of the active-admin repo (https://github.com/activeadmin/activeadmin/issues/5502):

See this blog post: http://sass.logdown.com/posts/7081811  
And this issue over at sass-rails: rails/sass-rails#420  

The ruby implementation of sass is already designated as "deprecated", so it's already in maintenance mode. They will be archiving the repo and not accepting issues or pull requests after March 29 2019. So it is going to eventually get stale.  

I would like to suggest this gem switch to sassc-rails or sassc, which uses the new C implementation of Sass.

**Comment by javierjulio** [comment]
@jkimmeyer keep in mind ActiveAdmin may **not** be changing to sassc after all because it may not be necessary. The PR for that has updated info in comparison to the issue submitted. https://github.com/activeadmin/activeadmin/pull/5504#issuecomment-456839445

**Comment by pmichaeljones** [comment]
What's up with this one guys?

**Comment by pmichaeljones** [comment]
@jkimmeyer @javierjulio Do you guys know if anyone is still maintaining this repo? Otherwise I'm going to fork it, switch the dependency to sassc and push a new version to RubyGems. Lemme know!

**Comment by javierjulio** [comment]
@pmichaeljones no need to do that dependency change: https://github.com/rails/sass-rails/pull/424

**Comment by pmichaeljones** [comment]
@javierjulio But this repo is depending on sass **spec.add_dependency "sass", [">= 3.3.0"]** and not sass-rails.

**Comment by javierjulio** [comment]
Ah sorry. In that case it will have to update. I wonder though if this should just rely on sass-rails instead since this is a Rails asset gem.

**Comment by pmichaeljones** [comment]
Relying on sass-rails, which is now just sassc-rails makes sense. Either way, our company site is still on Foundation 5 and doesn't plan on upgrading to 6, so I might just make a new gem for this issue.

**Comment by javierjulio** [comment]
Just to follow up, `foundation-rails` should be updated to depend on either `sassc-rails` or `sass-rails`. The difference is that the latter is just a thin wrapper around the former with template generation capability. From my understanding `sass-rails` will stick around to support that case and to be maintained within the Rails organization.

**Comment by keilmillerjr** [comment]
Any reason PR isn't accepted on this open issue?

```
Post-install message from sass:

Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/posts/7828841
```

**Comment by badpk** [comment]
this issue has still not been fixed 8 months after the end of life of the sass gem

**Comment by dougjohnston** [comment]
Agreed, it would be nice to get an update on this issue, especially since there is a PR #291 exists for it.

It appears that this gem is only receiving Foundation version updates, which are definitely welcome (thank you, maintainers ❤️ ), but it would be nice if some of these other issues could get a bit of attention as well.
