### ISSUE TITLE
is-reveal-open and turbolinks

### ISSUE THREAD

**Issue by haroldus-** [foundation/foundation-rails#290]
- place a link in your reveal modal to another part of your app enabled with turbolinks
- click the link
- sometimes the screen is frozen
- inspect the html document and the `is-reveal-open` class is present
- remove the class and all returns to normal

Perhaps there is a way to prevent this behaviour without a custom workaround.

**Comment by akaspick** [comment]
Same issue here.  Destroying or closing the dialog in one of the turbolinks events before navigating away doesn't seem to remove the `is-reveal-open` class.

**Comment by akaspick** [comment]
Well, I had some other issues with the modal not closing properly and now I've settled on the following as a solution that seems to work just fine now:

```
$(document).on('turbolinks:before-cache', function(evt) {
  $(`#dialog`).foundation('close')
})
```

**Comment by akaspick** [comment]
Noticed more issues when using reveal and turbolinks.  If you navigate to a page that uses a reveal modal, and then click back and then forward again via the history, multiple reveal divs are created with the same dom id.  Even if you close the modal before navigating away, the multiple reveal divs appear.

I have no current solution for this so far.

**Comment by jokrah** [comment]
Any updates on this? It's still an issue using the latest versions for both
