### ISSUE TITLE
Updating from 6.4.3 to 6.5

### ISSUE THREAD

**Issue by aksharj** [foundation/foundation-rails#303]
Hi,

In my rails 5 application, i am trying to update foundation version from `6.4.3 to 6.5` but get this error

```
couldn't find file 'foundation.core.js' with type 'application/javascript'
Checked in these paths: 
```

Any help on how to upgrade the gem to 6.5 would be really helpful.

Thanks.

**Comment by ahmad19** [comment]
I have just upgraded to rails 6 and i am also facing the same issue.

**Comment by frenkel** [comment]
Follow [my instructions](https://github.com/foundation/foundation-rails/issues/294#issuecomment-984682679) to fix this.
