### ISSUE TITLE
Maintained?

### ISSUE THREAD

**Issue by capripot** [foundation/foundation-rails#304]
Hi! I can't help but notice this project is not maintained anymore.
Do you need to maintain it?
Would activating Github sponsor help maintaining the project? I know some big names use Foundation sites. Could we ask a participation from them?

Cheers

**Comment by MicahBrown** [comment]
Any update on this? Foundation `6.7.4` is out now, and this gem is still on `6.6.2.0`

**Comment by javierm** [comment]
I see the version [has been changed to 6.7.5](https://github.com/foundation/foundation-rails/commit/94508cfa5) :thinking:. @joeworkman Are there any plans to publish the new version at rubygems?

**Comment by CARocha** [comment]
any update for this issues?
